Audtari/Audtari

package-lock.json
package.json

Updating the package.json to get boilerplate working
**Make sure to createdb audtari **
---

initial kermit

---

.gitignore
client/components/SpeechTest.js
client/routes.js
script/lib/p5.speech.js

speech component renders

---

client/components/Pong.js

pushing to master

---

client/components/Pong.js

added dictionaries

---

client/components/Pong.js
client/index.js
package-lock.json
package.json

initial firebase setup

---

client/components/PongMulti.js
client/routes.js

* [x ] added PongMulti.js and the /multi route
* [x ] /multi renders a game that is live updating to the firebase database
---

Firebase database update function rendering in the database

---

client/components/Lobby.js

Able to  add current user to the database
---

able to add userId to database

---

client/components/Lobby.js

Logic for conditional room assignment

---

client/components/Lobby.js
client/components/PongMulti.js

When you join a room, your user is assigned to that room and that specific room in the database gets updated game state
---

Lobby connection

---

client/components/PongMulti.js

Ball values from database instead of local

---

client/components/PongMulti.js

ball reset changes

---

client/components/PongMulti.js

Game is connected!

---

client/components/PongMulti.js

Back 2 Lobby button

---

client/components/Lobby.js
client/components/PongMulti.js
client/components/SignInScreen.js
client/index.js

Countdown timer

---

client/components/PongMulti.js

fixed re-join bug

---

client/components/Lobby.js
client/components/PongMulti.js

Post beta test

---

client/components/Dialog.js
client/components/Lobby.js
client/components/PongMulti.js
client/components/SignInScreen.js
package-lock.json
package.json
public/index.html
public/style.css

Added styling, alert boxes, and fixed score in database

---

client/components/PongMulti.js

Added timer in between scores in mp pong. changed ball speed and dealt with some hit detection issues

Pong tweaks

---

client/components/Lobby.js
client/components/PongMulti.js
client/components/navbar.js
public/style.css

Memorial Day weekend styling tweaks

---

public/style.css

Centering of games

---

client/components/Breakout/sketch.js
client/components/PongMulti.js

added ready up button and text to breakput and pong multi
